spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
mybatis:
  mapper-locations: classpath:com/example/springboot/mapper/*.xml
  type-aliases-package: com.example.springboot.pojo



